export const ActionTypes = {
  ADD_CATEGORY: 'ADD_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  ADD_SUBCATEGORY: 'ADD_SUBCATEGORY',
  UPDATE_SUBCATEGORY: 'UPDATE_SUBCATEGORY',
  DELETE_SUBCATEGORY: 'DELETE_SUBCATEGORY',
  SAVE_CATEGORIES: 'SAVE_CATEGORIES',
};
